### ISSUE TITLE
[WTD] SCCM Apps Inclusion Articles

### ISSUE THREAD

**Issue by SyntaxC4** [MicrosoftDocs/SCCMdocs#1553]
In support of #1550, here is a list of articles with line numbers of where non gender neutral language is present.

- [x] [monitor-app-usage-with-software-metering.md   Line   #161](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/apps/deploy-use/monitor-app-usage-with-software-metering.md#L161)
- [x]   [monitor-app-usage-with-software-metering.md Line   #164](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/apps/deploy-use/monitor-app-usage-with-software-metering.md#L164)
-   [x] [monitor-app-usage-with-software-metering.md Line   #168](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/apps/deploy-use/monitor-app-usage-with-software-metering.md#L168)
