### ISSUE TITLE
[WTD] SCCM Core Inclusion Articles

### ISSUE THREAD

**Issue by SyntaxC4** [MicrosoftDocs/SCCMdocs#1554]
In support of #1550, here is a list of articles with line numbers of where non gender neutral language is present.

- [x]   [example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md   Line   #31](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/clients/deploy/example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md#L31)
-   [x]   [example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md   Line   #33](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/clients/deploy/example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md#L33)
- [x]   [example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md   Line   #37](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/clients/deploy/example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md#L37)
-   [x]   [example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md   Line   #56](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/clients/deploy/example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md#L56)
- [x]   [example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md   Line   #62](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/clients/deploy/example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md#L62)
-   [x]   [example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md   Line   #64](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/clients/deploy/example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md#L64)
- [x]   [example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md   Line   #74](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/clients/deploy/example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md#L74)
-   [x]   [example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md   Line   #76](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/clients/deploy/example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md#L76)
- [x]   [example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md   Line   #80](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/clients/deploy/example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md#L80)
-   [x]   [example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md   Line   #88](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/clients/deploy/example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md#L88)
- [x]   [example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md   Line   #106](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/clients/deploy/example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md#L106)
-   [x]   [example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md   Line   #111](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/clients/deploy/example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md#L111)
- [x]   [example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md   Line   #113](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/clients/deploy/example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md#L113)
-   [x]   [example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md   Line   #115](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/clients/deploy/example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md#L115)
- [x]   [example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md   Line   #117](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/clients/deploy/example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md#L117)
-   [x]   [example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md   Line   #119](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/clients/deploy/example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md#L119)
- [x]   [example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md   Line   #121](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/clients/deploy/example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md#L121)
-   [x]   [example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md   Line   #123](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/clients/deploy/example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md#L123)
- [x]   [example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md   Line   #125](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/clients/deploy/example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md#L125)
-   [x]   [example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md   Line   #127](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/clients/deploy/example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md#L127)
- [x]   [example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md   Line   #138](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/clients/deploy/example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md#L138)
-   [x]   [example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md   Line   #142](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/clients/deploy/example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md#L142)
- [x]   [example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md   Line   #158](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/clients/deploy/example-scenario-for-deploying-and-managing-clients-on-windows-embedded-devices.md#L158)
-   [ ] [mms2019docathon.md Line   #95](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/misc/mms2019docathon.md#L95)
- [ ] [introduction.md Line   #124](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/understand/introduction.md#L124)
-   [ ] [introduction.md Line   #128](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/understand/introduction.md#L128)
- [ ] [introduction.md Line   #129](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/understand/introduction.md#L129)
-   [ ] [introduction.md Line   #130](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/understand/introduction.md#L130)
- [ ] [introduction.md Line   #164](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/understand/introduction.md#L164)
-   [ ] [introduction.md Line   #168](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/understand/introduction.md#L168)
- [ ] [introduction.md Line   #172](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/understand/introduction.md#L172)
-   [ ] [introduction.md Line   #196](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/understand/introduction.md#L196)
- [ ] [introduction.md Line   #200](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/core/understand/introduction.md#L200)

**Comment by mestew** [comment]
Verified all files in list have been edited.
