### ISSUE TITLE
[WTD] SCCM Protect Inclusion Articles

### ISSUE THREAD

**Issue by SyntaxC4** [MicrosoftDocs/SCCMdocs#1555]
In support of #1550, here is a list of articles with line numbers of where non gender neutral language is present.

- [ ]   [scenarios-endpoint-protection.md Line   #63](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/protect/deploy-use/scenarios-endpoint-protection.md#L63)
-   [ ] [scenarios-endpoint-protection.md Line   #64](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/protect/deploy-use/scenarios-endpoint-protection.md#L64)
- [ ] [scenarios-endpoint-protection.md Line   #66](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/protect/deploy-use/scenarios-endpoint-protection.md#L66)
-   [ ] [scenarios-endpoint-protection.md Line   #68](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/protect/deploy-use/scenarios-endpoint-protection.md#L68)
- [ ] [scenarios-endpoint-protection.md Line   #71](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/protect/deploy-use/scenarios-endpoint-protection.md#L71)
-   [ ] [scenarios-endpoint-protection.md Line   #74](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/protect/deploy-use/scenarios-endpoint-protection.md#L74)
- [ ] [scenarios-endpoint-protection.md Line   #78](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/protect/deploy-use/scenarios-endpoint-protection.md#L78)

**Comment by Khairunj** [comment]
[WTD] picking up this issue for gender inclusive writing
