### ISSUE TITLE
[WTD] SCCM Security Update Inclusion Articles

### ISSUE THREAD

**Issue by SyntaxC4** [MicrosoftDocs/SCCMdocs#1556]
In support of #1550, here is a list of articles with line numbers of where non gender neutral language is present.

- [x]   [example-scenario-deploy-monitor-monthly-security-updates.md Line   #35](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/sum/deploy-use/example-scenario-deploy-monitor-monthly-security-updates.md#L35)
- [x]   [example-scenario-deploy-monitor-monthly-security-updates.md Line   #40](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/sum/deploy-use/example-scenario-deploy-monitor-monthly-security-updates.md#L40)
-   [x] [example-scenario-deploy-monitor-monthly-security-updates.md Line   #48](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/sum/deploy-use/example-scenario-deploy-monitor-monthly-security-updates.md#L48)
- [x]   [example-scenario-deploy-monitor-monthly-security-updates.md Line   #55](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/sum/deploy-use/example-scenario-deploy-monitor-monthly-security-updates.md#L55)
-   [x] [example-scenario-deploy-monitor-monthly-security-updates.md Line   #62](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/sum/deploy-use/example-scenario-deploy-monitor-monthly-security-updates.md#L62)
- [x]   [example-scenario-deploy-monitor-monthly-security-updates.md Line   #66](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/sum/deploy-use/example-scenario-deploy-monitor-monthly-security-updates.md#L66)
-   [x] [example-scenario-deploy-monitor-monthly-security-updates.md Line   #71](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/sum/deploy-use/example-scenario-deploy-monitor-monthly-security-updates.md#L71)
- [x]   [example-scenario-deploy-monitor-monthly-security-updates.md Line   #78](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/sum/deploy-use/example-scenario-deploy-monitor-monthly-security-updates.md#L78)
-   [x] [example-scenario-deploy-monitor-monthly-security-updates.md Line   #82](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/sum/deploy-use/example-scenario-deploy-monitor-monthly-security-updates.md#L82)
- [x]   [example-scenario-deploy-monitor-monthly-security-updates.md Line   #84](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/sum/deploy-use/example-scenario-deploy-monitor-monthly-security-updates.md#L84)
-   [x] [example-scenario-deploy-monitor-monthly-security-updates.md Line   #87](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/sum/deploy-use/example-scenario-deploy-monitor-monthly-security-updates.md#L87)

**Comment by Khairunj** [comment]
[WTD]: Editing the file for gender inclusive project during write the docs conference

**Comment by Khairunj** [comment]
[WTD]; The user name John is referred many times in this document so not updated the document but making a comment only per Cory's instructions. @SyntaxC4 as fyi

**Comment by 1RedOne** [comment]
@aczechowski for this doc, could it be made more inclusive by switching from a user, in this case someone named John, to an unnamed party like so

_Currently_
>In this scenario, John is the Configuration Manager administrator at Woodgrove Bank. John needs to create a software update deployment strategy with the following conditions and requirements:  

_Proposed_
>In this scenario, the Configuration Manager administrator at Woodgrove Bank needs to create a software update deployment strategy with the following conditions and requirements:  

Or, might it be better to use a gender neutral name?  I read the guidelines but scenario documentation wasn't mentioned there.

**Comment by aczechowski** [comment]
Hi @1RedOne, some words of wisdom from @mestew : 

> we should try to finish stripping out all gendered names. We went with "the admin" and "the user" and it seems to have worked out well. 

It looks like your proposal aligns with that.

Thanks for helping out with this effort! 😄

**Comment by mestew** [comment]
Item completed.
