### ISSUE TITLE
[WTD] SCCM Mobile Device Inclusion Articles

### ISSUE THREAD

**Issue by SyntaxC4** [MicrosoftDocs/SCCMdocs#1557]
In support of #1550, here is a list of articles with line numbers of where non gender neutral language is present.

- [x]   [enroll-devices-with-device-enrollment-manager.md Line   #22](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/mdm/deploy-use/enroll-devices-with-device-enrollment-manager.md#L22)
- [x]   [enroll-devices-with-device-enrollment-manager.md Line   #38](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/mdm/deploy-use/enroll-devices-with-device-enrollment-manager.md#L38)
-   [x] [manage-mobile-devices-with-exchange-activesync.md Line   #37](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/mdm/deploy-use/manage-mobile-devices-with-exchange-activesync.md#L37)
- [x] [toolkit-reference.md Line   #3251](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/mdt/toolkit-reference.md#L3251)
-   [ ] [use-the-mdt.md Line   #7974](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/mdt/use-the-mdt.md#L7974)
- [ ]   [user-driven-installation-developers-guide.md Line   #449](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/mdt/user-driven-installation-developers-guide.md#L449)
-   [ ] [user-driven-installation-developers-guide.md Line   #3639](https://github.com/MicrosoftDocs/SCCMdocs/edit/master/sccm/mdt/user-driven-installation-developers-guide.md#L3639)

**Comment by Khairunj** [comment]
[WTD]: Picking up the file for write the docs conference for inclusive writing
